#!/usr/bin/env python

import os
import subprocess
import sys
from lib import execute, file_exists


slethkit_path="./vendor/sleuthkit"


def main():
    print("Prepare sleutkit library")
    if not file_exists(slethkit_path + "/configure"):
        print("  - Bootstrap")
        execute("./bootstrap", cwd=slethkit_path)

    if not file_exists(slethkit_path + "/Makefile"):
        print("  - Configure")
        config_cmd = ["./configure"]
        env = os.environ

        config = os.getenv("TSK_JS_CONFIG_ARGS")
        if config is not None:
            config_cmd += config.split(',')

        env_custom = os.getenv("TSK_JS_CONFIG_ENV")
        if env_custom is not None:
            for env_pair in env_custom.split(','):
                key, value = env_pair.split('=')
                env[key] = value

        execute(config_cmd, cwd=slethkit_path, env=env)

    print("Build sleutkit library")
    execute("make", cwd=slethkit_path)


if __name__ == '__main__':
    sys.exit(main())
