#!/usr/bin/env python

import os
import subprocess
import sys
from lib import execute, rmdir

config = {
    "docsDir": "./docs",
    "imageUser": "imgspy",
    "imageName": "docs-tsk-js"
}

def main():
    print("Build documentation")
    execute([
        "npm", "run", "doc:build"
    ])

    config["imageTag"] = config["imageUser"] + "/" + config["imageName"]
    print("Build docker image")
    execute([
        "docker", "build",
        "-t", config["imageTag"],
        config["docsDir"]
    ], print_stdout=True, root=True)

    print("Publish image")
    execute([
        "docker", "push",
        config["imageTag"]
    ], print_stdout=True, root=True)

    print("Refresh image")
    execute([
        "oc", "import-image",
        config["imageName"]
    ])


if __name__ == '__main__':
    sys.exit(main())
