#!/usr/bin/env python

import sys
from lib import execute


def main():
    print("Running tests")
    execute(["node", "test.js"], cwd="./test")
    print("Tests ok")


if __name__ == '__main__':
    sys.exit(main())
